<a href="https://colab.research.google.com/github/ddah0329/Study_BigData/blob/main/Ch01/_02_covariance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

### Weight이 70, 65, 50일 경우

In [ ]:
# H = height  W = weight
H = np.array([180, 170, 160])
W = np.array([70, 65, 50])

In [ ]:
H_mean = np.mean(H)
H

array([180, 170, 160])

In [ ]:
W_mean = np.mean(W)
W

array([70, 65, 50])

In [ ]:
# 공분산(coveriance)
Cov = (((H[0] - H_mean) * (W[0] - W_mean))+((H[1] - H_mean) * (W[1] - W_mean))+((H[2] - H_mean) * (W[2] - W_mean)))/3
Cov

66.66666666666667

In [ ]:
H_std = np.std(H)
W_std = np.std(W)

In [ ]:
# 방법 1
Rel = Cov/H_std/W_std
Rel

0.9607689228305227

In [ ]:
# 방법 2
Cov / (H_std * W_std)

0.9607689228305227

### Weight이 50, 60, 70일 경우
순서가 내림차순일때와 오른차순일때의 값이 다르다.

In [ ]:
# H = height  W = weight
Hh = np.array([180, 170, 160])
Ww = np.array([50, 60, 70])

In [ ]:
Hh_mean = np.mean(Hh)
Hh

array([180, 170, 160])

In [ ]:
Ww_mean = np.mean(Ww)
Ww

array([50, 60, 70])

In [ ]:
# 공분산(coveriance)
CovRe = (((Hh[0] - Hh_mean) * (Ww[0] - Ww_mean))+((Hh[1] - Hh_mean) * (Ww[1] - Ww_mean))+((Hh[2] - Hh_mean) * (Ww[2] - Ww_mean)))/3
CovRe

-66.66666666666667

In [ ]:
Hh_std = np.std(Hh)
Ww_std = np.std(Ww)

In [ ]:
RelRe = CovRe/Hh_std/Ww_std
RelRe

-1.0